# 1. Create a 3x3x3 array with random values 

In [7]:
import numpy as np



In [4]:
a = np.random.random((3,3,3))
a

array([[[0.73425846, 0.03224643, 0.58244646],
        [0.23767806, 0.96272879, 0.9278833 ],
        [0.26626694, 0.26934477, 0.33452925]],

       [[0.87227662, 0.39647848, 0.71103793],
        [0.63130317, 0.98901324, 0.48901574],
        [0.08361545, 0.64339948, 0.04802322]],

       [[0.96932972, 0.67778752, 0.54958056],
        [0.1227728 , 0.87237972, 0.69964137],
        [0.92262504, 0.10650559, 0.83187785]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [5]:
a = np.diag(1+np.arange(4),k=-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [6]:
a = np.zeros((8,8),dtype=int)
a[1::2,::2]=1
a[::2,1::2]=1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [11]:
A=np.random.random((5,5))
Amax,Amin = A.max(),A.min()
A=(A-Amin)/(Amax-Amin)
A

array([[0.60128272, 0.06375115, 0.04135297, 0.29052082, 0.88990494],
       [0.6853474 , 0.97340469, 0.        , 0.44471676, 0.85986719],
       [0.40441194, 0.41867682, 0.88993405, 0.63640171, 0.67203129],
       [0.29023804, 0.34167891, 0.81416964, 0.13636434, 1.        ],
       [0.14379268, 0.92782936, 0.51932038, 0.61035945, 0.71954398]])

# 5.  How to find common values between two arrays?

In [13]:
array1 = np.array([0,10,20,40,60])
print("array1:",array1)
array2 = [10,20]
print("array2:",array2)
print("common values between two arrays:")
print(np.intersect1d(array1,array2))

array1: [ 0 10 20 40 60]
array2: [10, 20]
common values between two arrays:
[10 20]


# 6.How to get the dates of yesterday, today and tomorrow?

In [17]:
yesterday = np.datetime64("today","D")-np.timedelta64(1,"D")
print("yesterday:",yesterday)
today = np.datetime64("today","D")
print("today:",today)
tomorrow = np.datetime64("today","D")+np.timedelta64(1,"D")
print("tomorrow:",tomorrow)

yesterday: 2020-07-27
today: 2020-07-28
tomorrow: 2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [19]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,1,5)
equal=np.allclose(a,b)
equal

False

# 8.Create random vector of size 10 and replace the maximum value by 0 

In [20]:
a=np.random.random(10)
a[a.argmax()]=0
a

array([0.        , 0.07256174, 0.05469197, 0.74403852, 0.31649502,
       0.65085959, 0.58327946, 0.4438627 , 0.66158837, 0.48860933])

# 9. How to print all the values of an array?

In [45]:
np.set_printoptions(threshold=np.inf)
a=np.zeros((25,25))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

# 10.Subtract the mean of each row of a matrix

In [33]:
x=np.random.rand(5,10)

y=x-x.mean(axis=1).reshape(-1,1)
y

array([[-0.37345895, -0.25368096, -0.04340941,  0.12512638, -0.51286888,
        -0.35652694,  0.26824137,  0.43807129,  0.40158271,  0.30692339],
       [-0.00829224, -0.22894504,  0.24918779, -0.36357996, -0.16936163,
         0.10492426, -0.44430151,  0.02999571,  0.43212931,  0.39824331],
       [ 0.22916759,  0.57500316,  0.32199148, -0.26721113, -0.38666431,
        -0.20788196, -0.09172495, -0.01145511, -0.01880532, -0.14241945],
       [-0.18582758, -0.21332396, -0.39041473,  0.47016871, -0.27983021,
        -0.05933323, -0.07573751,  0.34124445,  0.36811783,  0.02493623],
       [-0.48117431,  0.23211288, -0.00520202,  0.00684684,  0.2723215 ,
         0.07600335,  0.23930928, -0.41904137,  0.25121862, -0.17239477]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [35]:
a=np.ones(10)
i=np.random.randint(0,len(a),20)
a+=np.bincount(i,minlength=len(a))
a


array([5., 4., 3., 3., 3., 3., 3., 3., 1., 2.])

# 12.How to get the diagonal of a dot product?

In [37]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(0,10,(3,3))
np.sum(a*b.T,axis=1)

array([ 48, 117,  36])

# 13.How to find the most frequent value in an array?

In [39]:
a=np.random.randint(0,10,50)
print(a)
print("rank:",np.bincount(a).argmax())

[3 6 4 2 7 9 8 3 5 0 8 7 9 1 8 6 6 0 3 9 7 9 6 0 3 7 4 6 4 4 6 4 7 4 6 7 1
 0 0 2 4 2 3 3 1 3 9 7 6 0]
rank: 6


# 14.How to get the n largest values of an array

In [40]:
a=np.arange(10000)
np.random.shuffle(a)
n=5
print(a[np.argpartition(-a,n)[:n]])

[9997 9998 9995 9996 9999]


# 15.How to create a record array from a regular array?

In [44]:
a=np.array([("hello",2.5,3),("world",3.6,2)])
r=np.core.records.fromarrays(a.T,names="coi1,coi2,coi3",formats="S8,f8,i8")